spec/index.html
This fixes #11.
This corrects an error in PR #4.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/12.html" title="Last updated on Feb 10, 2023, 3:50 PM UTC (35259c1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/12/389dc7c...35259c1.html" title="Last updated on Feb 10, 2023, 3:50 PM UTC (35259c1)">Diff</a>
=> GH-11: Put section 'SPARQL Algebra' at the right level

spec/index.html
#7 clarification-query-1
There is no substantive change here because the rules of function evaluation apply.
It is correcting the explanation of the `IN` operator as noted by the original errata report. It also applies to `NOT IN`.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/15.html" title="Last updated on Feb 24, 2023, 11:52 AM UTC (49cc904)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/15/b64a563...49cc904.html" title="Last updated on Feb 24, 2023, 11:52 AM UTC (49cc904)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/15.html" title="Last updated on Feb 26, 2023, 9:48 AM UTC (78f0670)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/15/b64a563...78f0670.html" …
=> GH-7: clarification-query-1

spec/index.html
The reason for this change is in the email thread at: 
https://lists.w3.org/Archives/Public/public-rdf-dawg-comments/2013Jul/0004.html
Summary: a processor can use the fact two value spaces are distinct to provide the result of `!=` where otherwise it would be an an error.
Thanks to Rob Vesse for the analysis.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/16.html" title="Last updated on Feb 26, 2023, 6:05 PM UTC (d45e1ac)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/16/b64a563...d45e1ac.html" title="Last updated on Feb 26, 2023, 6:05 PM UTC (d45e1ac)">Diff</a>
=> GH-7: clarification-query-2

spec/index.html
https://www.w3.org/2013/sparql-errata#errata-query-3
This fixes an obvious mistake in the grammar.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/20.html" title="Last updated on Mar 6, 2023, 7:13 PM UTC (b75d98f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/20/7de93fb...b75d98f.html" title="Last updated on Mar 6, 2023, 7:13 PM UTC (b75d98f)">Diff</a>
=> errata-query-3

spec/index.html
This PR resolves [clarification-query-3](https://www.w3.org/2013/sparql-errata#clarification-query-3) by rephrasing the equality definition.
I also had to update some of the references, as they were pointing to outdated specs.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/17.html" title="Last updated on Mar 15, 2023, 6:10 PM UTC (31a68e6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/17/7de93fb...31a68e6.html" title="Last updated on Mar 15, 2023, 6:10 PM UTC (31a68e6)">Diff</a>
=> Resolve clarification-query-3, #7

spec/index.html
See the email [public-rdf-dawg-comments/2015Jun/0000.html](https://lists.w3.org/Archives/Public/public-rdf-dawg-comments/2015Jun/0000.html).
It is not possible to expand the logical "or" condition in the definition of diff into a union because of the ∀ μ′ / ∀ μ2.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/29.html" title="Last updated on Mar 22, 2023, 9:07 PM UTC (7a7216d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/29/7144771...7a7216d.html" title="Last updated on Mar 22, 2023, 9:07 PM UTC (7a7216d)">Diff</a>
=> errata-query-7,7a (#29)

spec/index.html
Makes `?specStatus=FPWD&pubDate=2023-04-01` as per WG editors guide.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/38.html" title="Last updated on Mar 26, 2023, 3:55 PM UTC (e3f30c4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/38/7144771...e3f30c4.html" title="Last updated on Mar 26, 2023, 3:55 PM UTC (e3f30c4)">Diff</a>
=> Rename section to pass specStatus

spec/index.html
https://www.w3.org/2013/sparql-errata#errata-query-12
Discussion:
https://lists.w3.org/Archives/Public/public-rdf-dawg-comments/2015Jun/0004
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/36.html" title="Last updated on Mar 25, 2023, 8:14 AM UTC (eb46e8a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/36/7144771...eb46e8a.html" title="Last updated on Mar 25, 2023, 8:14 AM UTC (eb46e8a)">Diff</a>
=> errata-query-12

spec/index.html
Fix an example.
See [public-sparql-dev/2014OctDec/0005](https://lists.w3.org/Archives/Public/public-sparql-dev/2014OctDec/0005.html).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/30.html" title="Last updated on Mar 27, 2023, 1:37 PM UTC (69aef3c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/30/7144771...69aef3c.html" title="Last updated on Mar 27, 2023, 1:37 PM UTC (69aef3c)">Diff</a>
=> errata-query-9 (#30)

spec/index.html
This is a small step to fix up the format for definition title/anchor to stop unintended line breaks. 
It puts definitions in a fixed format, so it'll be easier to convert to reSpec.
```
<b>Definition:</b>
<div id="defn_RDFTerm">
<b>RDF Term</b>
</div>
```
becomes 
```
<p><b>Definition: <div id="defn_RDFTerm">RDF Term</b></p>
```
along with a variant that has `<p><b>Definition:</b></p>`.
It's done by script. It may conflict with other open PRs - if so, it's a matter of running the script again.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/32.html" title="Last updated on Mar 27, 2023, 6:00 PM UTC (88dd4f3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/32/e1a135e...88dd4f3.html" title="Last updated on Mar 27, 2023, 6:00 PM UTC …
=> Fix up definition formatting and anchor

spec/index.html, spec/local.css
This is an attempt to get preview working for PR's. 
The problem seems to be that local.css is not being placed into the PR preview folder.
With this PR, the preview should look better.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/44.html" title="Last updated on Mar 29, 2023, 10:24 AM UTC (669b878)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/44/d4bc873...669b878.html" title="Last updated on Mar 29, 2023, 10:24 AM UTC (669b878)">Diff</a>
=> Inline local.css for 'preview'

spec/index.html
This fixed the external links from link checker report for XQuery, XML Schema, and RDF MT.
RDF Semantics (1.1) did not preserve the fragments of RDF MT (1.0)
[TR/XQuery ](https://www.w3.org/TR/xquery/) is now an informational redirection page.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/48.html" title="Last updated on Apr 2, 2023, 9:49 AM UTC (cbb417a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/48/882acc7...cbb417a.html" title="Last updated on Apr 2, 2023, 9:49 AM UTC (cbb417a)">Diff</a>
=> Address link checker report

spec/index.html
This PR makes the function name, section name, and use in examples for functions case-consistent with the grammar.
Aggregate functions are not touched.
Any choices involve a degree of personal preference, especially for the `is*` functions.
e.g. `STR`
e.g. `isBLANK`
except in the case of langMATCHES which is LANGMATCHES in the grammar.
It is `sameTerm` in the grammar currently.
There is a CSS change in this PR.
The `text-transform: uppercase` on `.operator` is removed.
Only `.operator` is used - all the uses are functions so it would be better to change to "function".
The original CSS currently forces uppercase for the definition. 
```
.operator	{ color: #3f3f5f;
text-transform: uppercase; }
.function	{ color: #3f3f5f;
}
```
***
<a …
=> Make function name and section name case-consistent

spec/index.html
Reformatting.
Some attributes were being split across lines.
This PR applies
```
s/href=[\s\n]+"/href="/gs;
s/data-cite=[\s\n]+"/data-cite="/gs;
s/class=[\s\n]+"/class="/gs;
```
then a step of visually looking for long lines (not in specifically formatted places like the grammar table) and fixing the long lines.
A few obvious spec text errors fixed in passing.
Because of the exiting specially formatted areas (grammar, operation and functions), it is unlikely a complete bulk reform will be successful.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/55.html" title="Last updated on Apr 13, 2023, 10:00 AM UTC (dc6b48c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/55/1845673...dc6b48c.html" title="Last updated on Apr 13, 2023, 10:00 AM UTC …
=> Fix split HTML attributes

spec/index.html
Instead, we refer to the concept of simple literals in RDF 1.2, and prefer explicit mentions to xsd:string in function definitions if relevant.
This also removes any examples where xsd:string and simple literals were shown as 2 distinct cases, to avoid confusion on them being different.
Closes #26
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/57.html" title="Last updated on Apr 28, 2023, 8:37 AM UTC (2a33051)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/57/47e09ed...2a33051.html" title="Last updated on Apr 28, 2023, 8:37 AM UTC (2a33051)">Diff</a>
=> Remove concepts of plain and simple literals

spec/index.html
* Remove "RDF URI Reference" : use IRI.
* Revert to "datatype IRI"
* Remove "corresponds" text because the terminology is now the same (at SPARQL 1.1, "RDF URI Reference" was on its way out and replaced by IRI, as per RDF 1.1 WG).
* Remove text referring to related from SPARQL 1.1 about RDF URI References (when RDF 1.1 had not yet published). 
Text about  "RDF URI Reference" mentions RDF Concepts which does not have "RDF URI Reference". This then get confusing because we do have "IRI Reference".
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/61.html" title="Last updated on May 1, 2023, 7:48 AM UTC (6e48cc9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/61/f17baf2...6e48cc9.html" title="Last updated on May 1, 2023, 7:48 AM UTC …
=> Use RDF 1.2 terminology

spec/index.html
Need to be a bit careful about "The IN operator is equivalent to the SPARQL expression:" Switching that text and the quoted text above would be better. 
Ditto NOT IN.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/68.html" title="Last updated on May 6, 2023, 10:06 AM UTC (05c4cbd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/68/9cd8860...05c4cbd.html" title="Last updated on May 6, 2023, 10:06 AM UTC (05c4cbd)">Diff</a>
=> Clarify IN and NOT IN

spec/index.html
This addresses [sparql-errata#errata-query-5](https://www.w3.org/2013/sparql-errata#errata-query-5).
This is part of #8.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/77.html" title="Last updated on May 14, 2023, 7:20 PM UTC (2d6f428)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/77/ed41ca1...2d6f428.html" title="Last updated on May 14, 2023, 7:20 PM UTC (2d6f428)">Diff</a>
=> errata-query-5: Aggregate functions can not be nested

spec/index.html
This addresses [sparql-errata#errata-query-4](https://www.w3.org/2013/sparql-errata#errata-query-4).
This is part of #8.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/70.html" title="Last updated on May 14, 2023, 7:18 PM UTC (e5e7387)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/70/b279bac...e5e7387.html" title="Last updated on May 14, 2023, 7:18 PM UTC (e5e7387)">Diff</a>
=> errata-query-4: CONCAT and COALESCE

spec/index.html
This PR is specifically for changing 'blank node label' to 'blank node identifier' in SPARQL Query.
Part of issue #66.
It will conflict with PR #65 because there are s/label/identifier/ changes in sections changed by PR #65. PR #65 should go in first, and then this PR get fixed up (which is why this PR is initially "draft").
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/69.html" title="Last updated on May 18, 2023, 6:07 PM UTC (c51df8f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/69/ed73056...c51df8f.html" title="Last updated on May 18, 2023, 6:07 PM UTC (c51df8f)">Diff</a>
=> Replace 'blank node label' by 'blank node identifier'

spec/index.html
This resolves #80.
This is an errata to  SPARQL 1.0.
The cardinality of an element _x_ in a project is the sum of cardinalities of all elements in the input that project to _x_.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/81.html" title="Last updated on May 23, 2023, 9:19 AM UTC (5e264eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/81/f80d5a8...5e264eb.html" title="Last updated on May 23, 2023, 9:19 AM UTC (5e264eb)">Diff</a>
=> Errata: projection cardinality

spec/index.html
Part of #22.
Resolves [errata-query-13](https://www.w3.org/2013/sparql-errata#errata-query-13).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/82.html" title="Last updated on May 23, 2023, 7:18 AM UTC (da82325)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/82/f80d5a8...da82325.html" title="Last updated on May 23, 2023, 7:18 AM UTC (da82325)">Diff</a>
=> Errata: Definition of Filter

spec/index.html
Part of issue #53 (Incorporate RFD-star CG report)
This is the SPARQL Grammar changes, and only those changes, to replace the table in [section 19.8](https://w3c.github.io/sparql-query/spec/index.html#sparqlGrammar).
This is not directly the content from the CG report because the complete SPARQL grammar in the report has various errors and omissions. The fragment earlier in the report is closer.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/78.html" title="Last updated on May 25, 2023, 5:11 PM UTC (a484316)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/78/57924ae...a484316.html" title="Last updated on May 25, 2023, 5:11 PM UTC (a484316)">Diff</a>
=> Update grammar for quoted triples and triple functions

spec/index.html
URLs where already pointing to 3.1
Related issue: #86
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/89.html" title="Last updated on Jun 1, 2023, 3:49 PM UTC (12d235e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/89/81781e8...12d235e.html" title="Last updated on Jun 1, 2023, 3:49 PM UTC (12d235e)">Diff</a>
=> Upgrades references to XPath from 2.0 to 3.1

spec/index.html
... as suggested by @kasei in https://github.com/w3c/sparql-query/issues/95#issuecomment-1584615608
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/98.html" title="Last updated on Jun 22, 2023, 5:40 PM UTC (8e30456)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/98/095c3a0...8e30456.html" title="Last updated on Jun 22, 2023, 5:40 PM UTC (8e30456)">Diff</a>
=> Turn the input to Group(..) and to Aggregation(..) into solution sequences

spec/index.html
rdf:langString is normative since RDF 1.1 and there is already a note just above to highlight rdf:langString usage
=> Removes the historical notes on rdf:langString datatype

spec/index.html
States that "set union" does not mandates deduplication.
Issue #91
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/93.html" title="Last updated on Jun 9, 2023, 2:46 PM UTC (df7795e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/93/81781e8...df7795e.html" title="Last updated on Jun 9, 2023, 2:46 PM UTC (df7795e)">Diff</a>
=> Adds a note on deduplication of triples produced by CONSTRUCT

spec/index.html
Avoids to point either to the section either to the definition
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/85.html" title="Last updated on May 27, 2023, 5:58 PM UTC (3c05b41)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/85/81781e8...3c05b41.html" title="Last updated on May 27, 2023, 5:58 PM UTC (3c05b41)">Diff</a>
=> Migrates XML Schema references to 1.1 and cleans up anchors

spec/index.html
As I argue in #94, the suggested fix for [errata-query-11](https://www.w3.org/2013/sparql-errata#errata-query-11) is not needed but a small renaming of variables may help to avoid the confusion that led to the errata. This PR implements my proposed variable renaming.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/109.html" title="Last updated on Jun 29, 2023, 11:48 AM UTC (d1efdf6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/109/ae554d5...d1efdf6.html" title="Last updated on Jun 29, 2023, 11:48 AM UTC (d1efdf6)">Diff</a>
=> errata-query-11

spec/index.html
... as pointed out in #99
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/108.html" title="Last updated on Jun 29, 2023, 10:56 AM UTC (dedb4d0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/108/ae554d5...dedb4d0.html" title="Last updated on Jun 29, 2023, 10:56 AM UTC (dedb4d0)">Diff</a>
=> Removes inconsistencies between the definitions of the set functions

spec/index.html
The previous text in 17.2 Filter Evaluation said:
> Apart from BOUND, COALESCE, NOT EXISTS and EXISTS, all functions and operators operate on RDF Terms and will produce a type error if any arguments are unbound.
This PR updates the text to also include reference to `IF`, `IN`, and `NOT IN`, and describes all of these as functional forms.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/117.html" title="Last updated on Aug 17, 2023, 4:27 PM UTC (7629bfc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/117/797575a...7629bfc.html" title="Last updated on Aug 17, 2023, 4:27 PM UTC (7629bfc)">Diff</a>
=> Update Filter Evaluation language to reference more functional forms.

spec/index.html
- unification of items in References - now all items are in capital letters
- ~~remove vCard from References - now vCard vocab is treated the same as FOAF vocab~~
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Sep 21, 2023, 4:31 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fsparql-query%2F973dbd729c4c691f004d541b93860bfda838ed7a%2Fspec%2Findex.html%3FisPreview%3Dtrue)
```
📡 HTTP …
```
=> capital letters in refs

spec/index.html
As I just noticed when writing https://github.com/w3c/sparql-query/pull/122#issuecomment-1730246199, in PR #98 I made a mistake in the definition of the 'Flatten' function. This PR fixes this mistake.
While the text in the definition was correct, the formula that illustrates of what form the sequence S is was wrong.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/123.html" title="Last updated on Sep 21, 2023, 8:39 PM UTC (1e22564)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/123/bced028...1e22564.html" title="Last updated on Sep 21, 2023, 8:39 PM UTC (1e22564)">Diff</a>
=> Fixes the definition of the Flatten function

spec/index.html
Related to the discussion in PR #122, this PR here demonstrates how I think the definition of the Sum function should be improved and how the corresponding example can be presented.
Note that this PR uses the feature of ReSpec to explicitly markup symbols in math formulas (as we are planning to use for the whole spec, as per #102). Hence, you can click on every symbol (including function names) and see where else in the section this symbol is used.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/124.html" title="Last updated on Oct 5, 2023, 7:04 PM UTC (ae8c77c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/124/bced028...ae8c77c.html" title="Last updated on Oct 5, 2023, 7:04 PM UTC (ae8c77c)">Diff</a>
=> Improves the section about the Sum set function

spec/index.html
I just realized that I made another smaller mistake in PR #98. This PR is meant to fix this mistake.
The mistake is in the definition of the (new) Dedup function that PR #98 introduces as a helper function within the definition of the [Aggregation operator](https://www.w3.org/TR/sparql12-query/#defn_algAggregation). In particular, the issue is that the definition of Dedup assumes that M(Ψ) is a sequence of RDF terms, which is not the case. Instead, M(Ψ) is a sequence of lists that are produced by the ListEval function, where each such list may contain RDF terms and errors (that may have occurred when evaluating any of the expressions that is given as an argument to the corresponding aggregate).
The fix that I am proposing in this PR is twofold: First, it makes explicit that M(Ψ) is a …
=> Fixes a mistake in Dedup function

spec/index.html
In the context of [discussing the new Card(..) function introduced](https://github.com/w3c/sparql-query/pull/108#issuecomment-1618880551) in PR #108, @afs [writes](https://github.com/w3c/sparql-query/pull/108#issuecomment-1618937017):
> `card[Ω]` evaluates to a function that gives the number of instances of `μ`.
>
> We could change that "multiplicity" or something based on that word ("multiplicity" seems a bit long but may be necessary).
This PR here is a proposal to address this comment. In particular, this PR introduces a function called 'multiplicity' with a definition that can be cross-referenced, and (currently) one place where this function is used (namely, in the definition of Filter). The latter is to demonstrate how it would look like to use this functions instead of the notation …
=> introduces a function called multiplicity to replace card[Ω](μ)

spec/index.html
As a follow-up to PR #124, which has improved the definitions of Sum, Min, Max, and GroupConcat, this PR introduces the same improved presentation style for the other set functions (Count, Avg, and Sample). Additionally, this PR adds links to the Flatten function in the definitions of all the set functions.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/127.html" title="Last updated on Oct 10, 2023, 9:15 AM UTC (0c735c0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/127/6afce45...0c735c0.html" title="Last updated on Oct 10, 2023, 9:15 AM UTC (0c735c0)">Diff</a>
=> Improves the definitions of Count, Avg, and Sample

spec/index.html
The functions Flatten(..) and Card(..) are currently defined at the end of [Sec.18.5.1 Aggregate Algebra](https://www.w3.org/TR/sparql12-query/#aggregateAlgebra), directly before [Sec.18.5.1.1 Set Functions](https://www.w3.org/TR/sparql12-query/#setFunctions). There is no explanation why these functions are needed.
Since the main purpose of these functions is to be helper functions that are used for defining the set functions in Sections 18.5.1.2 to 18.5.1.8, I find it much more natural to introduce these two functions in [Sec.18.5.1.1 Set Functions](https://www.w3.org/TR/sparql12-query/#setFunctions).
Hence, this PR moves the definitions of these two functions into [Sec.18.5.1.1 Set Functions](https://www.w3.org/TR/sparql12-query/#setFunctions) and adds a sentence that introduces the …
=> Moves the definition of Flatten(..) and Card(..)

spec/index.html
This PR implements the change that @afs suggested in PR #132. See https://github.com/w3c/sparql-query/pull/132#discussion_r1417439560 for the original comment with this change suggestion.
I have to admit that, even with this change, I still don't understand what exactly the sentence is supposed to say. So, maybe we can improve the sentence even more. In particular, the following points still confuse me in this sentence.
1. In the context of talking about "the result of ListEval," the sentence mentions "solutions containing error values." Assuming "solutions" here means solution mappings (as everywhere else in the spec), this part of the sentence doesn't make sense. Solutions cannot contain "error values." By definition!
2. Related to the previous point, the result of ListEval is not a …
=> Improvement to sentence about grouping and errors

spec/index.html
… in Section 18.2.4.4.
In [Section 18.2.4.4 of version 1.1](https://www.w3.org/TR/sparql11-query/#sparqlSelectExpressions) of the spec, the algorithm looks as follows.
In [Section 18.2.4.4 of our current draft of version 1.2](https://www.w3.org/TR/sparql12-query/#sparqlSelectExpressions), it looks as follows.
Notice how the `selItem ...` part is rendered weirdly.
This PR fixes this issue.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/139.html" title="Last updated on Feb 22, 2024, 1:28 PM UTC (33b2454)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/139/1e15e55...33b2454.html" title="Last updated on Feb 22, 2024, 1:28 PM UTC (33b2454)">Diff</a>
=> Fixes the algorithm for translating SELECT expressions

spec/index.html
… by making them more explicit and, in particular, by avoiding the use of symbols that denote sets of things and that have been introduced somewhere else before. These changes should make these definitions easier to read.
This PR is related to issue #137. However, while that issue is only about the definition of the notion of a variable, this PR applies similar improvements also in the other definitions within Section 18.1.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/138.html" title="Last updated on Feb 21, 2024, 10:04 AM UTC (50935fc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/138/3250785...50935fc.html" title="Last updated on Feb 21, 2024, 10:04 AM UTC (50935fc)">Diff</a>
=> Improves the definitions in Sec.18.1 (Initial Definitions)

spec/index.html
Addresses the two points in issue #136
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/140.html" title="Last updated on Feb 23, 2024, 5:54 PM UTC (9687c06)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/140/1e15e55...9687c06.html" title="Last updated on Feb 23, 2024, 5:54 PM UTC (9687c06)">Diff</a>
=> Clarifications about the use of ToList in algebra expressions

spec/index.html
as in https://github.com/w3c/sparql-query/pull/139/files#r1501003927, to match all other algorithm `for each` statements
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/sparql-query/pull/141.html" title="Last updated on Feb 23, 2024, 6:10 PM UTC (077b904)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/141/3597928...TallTed:077b904.html" title="Last updated on Feb 23, 2024, 6:10 PM UTC (077b904)">Diff</a>
=> remove errant colon

spec/index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/146.html" title="Last updated on Apr 26, 2024, 11:04 AM UTC (6932845)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/146/4806e12...6932845.html" title="Last updated on Apr 26, 2024, 11:04 AM UTC (6932845)">Diff</a>
=> Add changelog to track changes, Closes #129

spec/index.html
This PR updates the SPARQL Grammar to include initial text direction syntax and functions. There is also a fix for nested reified triples.
This replaces the grammar changes in #113 in order to get all the SPARQL 1.2 grammar changes into the working draft. 
The rest of #113 (updated) with the the function definitions will follow separately.
Initial text direction functions:
* Functions `isLang`, `isLangDir`, `LANGDIR`, and `STRLANGDIR`.
Changes to reification:
* Fix: allow reified triples to be nested.
* Fix: remove production `ReifiedTripleData` (removal causes renumbering)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/153.html" title="Last updated on Sep 18, 2024, 6:28 PM UTC (3590523)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/15 …
=> SPARQL Grammar: initial text direction; nested reified triples

spec/index.html
Closes #28
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/152.html" title="Last updated on Sep 19, 2024, 6:33 AM UTC (44d060e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/152/ca14da9...44d060e.html" title="Last updated on Sep 19, 2024, 6:33 AM UTC (44d060e)">Diff</a>
=> Use RDF Dataset definition from RDF Concepts

spec/index.html
This closes: #166
The definition  of "RDF Dataset Merge" is moving to RDF Semantics. This PR does the sparql-query part.
Two commits:
* Remove the definition of RDF Dataset Merge
* Suggestion -- put in a box for "dataset" - but not the "Definition" text for RDF dataset.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/167.html" title="Last updated on Nov 1, 2024, 3:41 PM UTC (c8a51aa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/167/78300a6...c8a51aa.html" title="Last updated on Nov 1, 2024, 3:41 PM UTC (c8a51aa)">Diff</a>
=> Remove the definition of RDF Dataset Merge

spec/index.html
This closes #170.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/171.html" title="Last updated on Nov 26, 2024, 5:55 PM UTC (d90c993)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/171/b163a60...d90c993.html" title="Last updated on Nov 26, 2024, 5:55 PM UTC (d90c993)">Diff</a>
=> Use ReSpec for RFC 2119 keywords

spec/index.html
What was section 17.1 is now 19.1 after the Functions and Operator version update.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/174.html" title="Last updated on Dec 15, 2024, 11:19 AM UTC (a2695ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/174/e884490...a2695ee.html" title="Last updated on Dec 15, 2024, 11:19 AM UTC (a2695ee)">Diff</a>
=> Update section number referred to in F&O

spec/index.html
This addresses #154
#112 has been used for a different discussion.
---
The SPARQL grammar already has the base direction update #153.
This PR adds the functions `LANGDIR`, `STRLANGDIR`, `hasLANGDIR` and `hasLANG`.
It includes the non-grammar content from #113 with comments incorporated.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/172.html" title="Last updated on Dec 20, 2024, 9:19 AM UTC (262dee4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/172/5dba9fd...262dee4.html" title="Last updated on Dec 20, 2024, 9:19 AM UTC (262dee4)">Diff</a>
=> Functions for the base direction feature

spec/index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/186.html" title="Last updated on Jan 23, 2025, 8:31 PM UTC (527c60a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/186/c073717...527c60a.html" title="Last updated on Jan 23, 2025, 8:31 PM UTC (527c60a)">Diff</a>
=> Add 'triple term' to list of RDF terms

spec/index.html
A small step - remove some unused CSS.
Change reference to RDF Concepts for IRI in casting table.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/193.html" title="Last updated on Feb 4, 2025, 11:19 AM UTC (c07711a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/193/d4c07b3...c07711a.html" title="Last updated on Feb 4, 2025, 11:19 AM UTC (c07711a)">Diff</a>
=> Remove some unused CSS; fix a link to IRI

spec/index.html
This closes #188
This closes #189 
* Call "SPARQL Request String", "SPARQL string" (original anchor still works)
"Request" is too oriented to protocol action
* SPARQL string is a RDF string that conforms to the grammar section
* More reSpec on definitions
* Exclude surrogates from unicode escape sequences (clarity - they are not allowed in RDF string)
Used more reSpec
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/190.html" title="Last updated on Jan 30, 2025, 8:50 AM UTC (4038a3b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/190/16f8a7a...4038a3b.html" title="Last updated on Jan 30, 2025, 8:50 AM UTC (4038a3b)">Diff</a>
=> SPARQL String. Unicode escapes exclude surrogates.

spec/index.html
* Reorder to put features first
* Add that surrogates are excluded in Unicode escape sequences
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/195.html" title="Last updated on Feb 8, 2025, 9:56 AM UTC (70ad502)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/195/610778f...70ad502.html" title="Last updated on Feb 8, 2025, 9:56 AM UTC (70ad502)">Diff</a>
=> Update changes section

spec/index.html
This closes #187.
This closes #25.
Changes:
* Rename `RDFterm-equal` as `sameValue`
* Reorder `sameTerm`, `sameValue`
* Reword `sameValue` (see #187)
* Bring definition/description of RDF term equality up-to-date - see related issue w3c/rdf-concepts#154
* Replace examples
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/194.html" title="Last updated on Apr 4, 2025, 2:02 PM UTC (0391ac4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/194/1dabcb9...0391ac4.html" title="Last updated on Apr 4, 2025, 2:02 PM UTC (0391ac4)">Diff</a>
=> Revise RDFterm-equal and function sameTerm. Rename RDFterm-equal to sameValue.

spec/index.html, spec/sparql.bnf
This closes #208.
Add `VERSION` to the SPARQL grammar.
Only the grammar table, changes section and the BNF file are touched by this PR.
+ one HTML fix introduced in an earlier PR when Echidna checks were not running.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/210.html" title="Last updated on Apr 25, 2025, 3:19 PM UTC (726486b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/210/e19fc4f...726486b.html" title="Last updated on Apr 25, 2025, 3:19 PM UTC (726486b)">Diff</a>
=> GH-208: SPARQL grammar for VERSION

spec/index.html
This PR fixes the typo mentioned in #213. Additionally, it removes a duplicate definition of the ToMultiset algebra operator.
Closes #213  /cc @pfps
=> Fixes typo in evaluation semantics of ToMultiSet

sparql-ns.ttl
* Corrects mistake: tehre was `sparql:logical-and` and also `sparql:operator-and`. Same for `or`. 
* Add `sparql:logical-not`
* Operations like `+` are functions. Make both a `sparql:Function` and a `sparql:Operator`
I don't think `sparql:Operator` adds anything. It is used for operations (functions, and some functional forms) that have specific operator-style syntax. But they are functions and functional forms - syntax goes away.
Proposal: also remove `sparql:Operator` - this is the second commit of the PR.
=> Namespace document cleanup

spec/index.html
This PR addresses #217 by extending the [definition of how to evaluate GRAPH patterns](https://www.w3.org/TR/sparql12-query/#defn_evalGraph) such that it now also considers blank nodes as possible graph names in an RDF dataset.
Additionally, the PR:
* changes the layout style of the changed definition such that it is consistent with the style of the other definitions in this part of the spec
* removes the introduction of the notation _Ω_(_x_) from the beginning of Section [18.3 Basic Graph Patterns](https://www.w3.org/TR/sparql12-query/#BasicGraphPattern)
* (this notation was used only in the definition that this PR changes and it was also not really clear; I have replaced it by something better directly in the changed definition now)
* removes the notation _D_[_i_] from the beginning of …
=> Consider bnode graph names in evaluation of Graph

spec/index.html
This is the next step related to #228 
Given the new option to directly link to the symbols of the algebraic syntax (as added by the previous PR, #227), this PR applies this option in Section [18.6.2 Evaluation Semantics](https://www.w3.org/TR/sparql12-query/#sparqlAlgebraEval) now. That is, every mention of such a symbol in this section is now linked to the definition of that symbol.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/243.html" title="Last updated on Jun 27, 2025, 3:47 PM UTC (580456f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/243/4345c7d...580456f.html" title="Last updated on Jun 27, 2025, 3:47 PM UTC (580456f)">Diff</a>
=> Adds links to algebraic syntax symbols within the evaluation semantics section

sparql-ns.ttl, spec/index.html
Closes #261
This PR adds `logical-not` in the same style as `logical-and` and `logical-or` and uses that for the `!` operator.
While `logical-not` and `fn:not` are similar, the domain of `logical-not` is not a restriction of `fn:not` because of non-literals ([Effective Boolean Value](https://www.w3.org/TR/sparql12-query/#ebv)).
Other uses of `fn:not` in the document are not changed - they are applied to only boolean values.
The PR also corrects the NS document (#261).
See also other issues in this area:
* #263 
* #264
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/262.html" title="Last updated on Aug 19, 2025, 9:53 AM UTC (95749e0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/262/a81b291...95749e0.html" title="Last updated on Aug 19, …
=> SPARQL logical-not

spec/index.html
This PR implements a few edit suggestions that @TallTed had on commit https://github.com/w3c/sparql-query/commit/f4977cecbcc42fbfb28ea77a728aaddaffe6a70c in PR #245 after the PR was already merged.
@TallTed, I included all your suggestions except for [the one about code-fencing the keyword SELECT](https://github.com/w3c/sparql-query/commit/f4977cecbcc42fbfb28ea77a728aaddaffe6a70c#r163944096). That one I left out because, in this part of the spec, there are a lot of mentions of SPARQL keyword and none of them is code-fenced. Thus, code-fencing just this one mention of "SELECT" would be inconsistent with respect to the rest of this part of the spec.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/259.html" title="Last updated on Aug 15, 2025, 12:28 PM UTC …
=> Minor edit suggestions by @TallTed

spec/index.html, spec/sparql.bnf
This closes: #279
The UnaryExpression production for `!` should allow `!!`.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/281.html" title="Last updated on Sep 4, 2025, 8:05 PM UTC (136da5c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-query/281/a4c493b...136da5c.html" title="Last updated on Sep 4, 2025, 8:05 PM UTC (136da5c)">Diff</a>
=> Grammar: UnaryExpression production for `!` should allow `!!`.
